### PR TITLE
Fix for issue #67 with an option

### PR DESCRIPTION
**Pull request by pmorch**
This should fix issue #67 and replace pull-request #69 .

### CODE REVIEW

**Comment by marklieberman** [comment]
What was the reason for simplifying the save promise? I did it using $q service to ensure that the promise resolution was part of the angular $digest cycle. http://jimhoskins.com/2012/12/17/angularjs-and-apply.html

**Comment by pmorch** [comment]
My thinking was: There already is a "real" ES6 promise, so why create a `$q` promise from that.

I'm ok with reverting my changes to the original save syncPromise and the new localPromise and use a $q promise for both. Or, perhaps I should leave the promises be as they are now, and then use Angular `$q.all()` instead of ES6 `Promises.all()`, to wrap both of them in `$q` goodness?

I'm not sure i fully understand how this could affect anything though, whether it is one or the other. "save" doesn't change the model/`$scope` at all, and the only place 'save' is called is further down in options.js where the promise is used thus:

        settings.save().then(() => {
          $scope.$broadcast('afterSettingsSaved');
          $scope.$broadcast('redraw');
        });

So Angular handles the resolution anyway.

But as I said, I'm happy to change it back to how it was. I'd just also like to understand what the detrimental effects of my changes are.

In light of FF57 already having been released and all, perhaps I should just make the changes and try to understand later?

Anything else, or is it then merge-worthy? :-)

**Comment by fotcorn** [comment]
Here is a compiled and signed version of FoxyGestures with this pull request applied:
https://ufile.io/oy1ik
Install it from Inside Firefox with File => Open File...
Works for me on Ubuntu/Firefox 57 without additional configuration.

**Comment by brickleroux** [comment]
@fotcorn 
Thank you for creating a test version. Works also for me on Arch x86_64/Firefox 57.

**Comment by pmorch** [comment]
I have to say that the compiled and signed version works for me in FF 58.0b4 Developer Edition but not in FF57 due to #104 (== #76?).

But then again, neither does vanilla Foxy Gestures, so that has nothing to do with this pull-request or with @fotcorn's signed version.

**Comment by AGCaesar** [comment]
@fotcorn 
Thanks a lot! I tried building this myself but failed due to me not having any Idea what to do. It works perfectly. Well at least until they fixed the underlying bug.

**Comment by marklieberman** [comment]
I'm swamped with work but I'll merge this and try to get a new version published to AMO this weekend.

**Comment by marklieberman** [comment]
I've published 1.1.0beta1 on AMO which includes this PR, a number of fixes for the built in commands, and localization. Could you guys test it out this week? I'l like to get some feedback and if there's no issues push it to release.

**Comment by cardamon** [comment]
I've been running it without problems since yesterday  :thumbsup:  :cake:

**Comment by AGCaesar** [comment]
I ran it for a day, worked well, but I moved back to the stable version with the patched FF version. Works perfectly now, no double clicking necessary :)

**Comment by marklieberman** [comment]
This is now published to AMO. Figures that the underlying bug got fixed around the same time.

**Pull request merged**
